#!/usr/bin/env python3
"""Audit every P2E calibration size generated by the released CA protocol."""

from __future__ import annotations

import argparse
import importlib
import json
import math
import sys
from collections import Counter
from pathlib import Path

import numpy as np
from sklearn.model_selection import train_test_split

try:
    from .verify_p2e_identity import in_theorem_domain
except ImportError:
    from verify_p2e_identity import in_theorem_domain


ROOT = Path(__file__).resolve().parents[2]
EXPECTED_SOURCE = (
    "Nabil-Ala/P2E_calibration@66cb1e1c76d1b1d3d133fe6cb3896c95d48b5974"
)
EXPECTED_CONTEXT_COUNTS = {"eca": 560, "weca_tune": 560, "weca_final": 560}
EXPECTED_BOUNDARY_COUNTS = {"eca": 33, "weca_tune": 25, "weca_final": 22}


def calibration_size_records(source: Path, input_manifest: dict) -> tuple[list[dict], object]:
    source_dir = source.resolve(strict=True) / "e-ca"
    sys.path.insert(0, str(source_dir))
    config = importlib.import_module("config")
    source_utils = importlib.import_module("utils")
    rows_by_task = {
        int(task["task_id"]): int(task["X_shape"][0])
        for task in input_manifest["tasks"]
    }
    records = []
    for dataset_name, task_id in config.DATASETS.items():
        row_count = rows_by_task[int(task_id)]
        for seed in config.seeds:
            temporary, _ = train_test_split(
                np.arange(row_count), test_size=0.15, random_state=seed
            )
            _, calibration = train_test_split(
                temporary, test_size=35 / 85, random_state=seed
            )
            n_calibration = len(calibration)
            permutation = np.random.default_rng(seed).permutation(n_calibration)
            quarter = n_calibration // 4
            split_one = permutation[:quarter]
            split_three = permutation[2 * quarter :]
            for model_index, model_name in enumerate(config.make_models(seed)):
                base = source_utils.random_subsample(
                    np.empty((n_calibration, 1)),
                    np.empty(n_calibration),
                    seed=seed + model_index,
                )
                contexts = {
                    "eca": len(base),
                    "weca_tune": len(np.intersect1d(base, split_one)),
                    "weca_final": len(np.intersect1d(base, split_three)),
                }
                for context, size in contexts.items():
                    records.append(
                        {
                            "dataset": dataset_name,
                            "task_id": int(task_id),
                            "seed": int(seed),
                            "model": model_name,
                            "context": context,
                            "n_calibration": int(size),
                            "alpha_times_rank_count": float(
                                config.alpha * (size + 1)
                            ),
                            "theorem_domain": in_theorem_domain(
                                size, config.alpha
                            ),
                        }
                    )
    return records, source_utils


def characterize_boundary_size(source_utils, n_calibration: int, alpha: float) -> dict:
    scaled = alpha * (n_calibration + 1)
    assert math.isclose(scaled, round(scaled), rel_tol=0.0, abs_tol=1e-12)
    c_value, s_value = source_utils.get_C_s(alpha, n_calibration)
    source_fn = source_utils.get_p_to_e("P2E", alpha, n_calibration)
    ranks = np.arange(1, n_calibration + 2, dtype=float) / (n_calibration + 1)
    values = np.asarray(source_fn(ranks), dtype=float)
    cutoff = int(round(scaled))
    expected_members = np.arange(1, n_calibration + 2) > cutoff
    source_members = values < 1.0 / alpha
    aon = np.zeros(n_calibration + 1, dtype=float)
    aon[:cutoff] = 1.0 / alpha
    return {
        "n_calibration": n_calibration,
        "alpha_times_rank_count": scaled,
        "source_C": float(c_value),
        "source_s": float(s_value),
        "source_mean_e": float(values.mean()),
        "source_zero_count": int(np.sum(values == 0.0)),
        "source_set_mismatches": int(np.sum(source_members != expected_members)),
        "maximum_float_deviation_from_exact_aon": float(
            np.max(np.abs(values - aon))
        ),
        "exact_aon_expectation": float(aon.mean()),
        "exact_aon_set_mismatches": int(
            np.sum((aon < 1.0 / alpha) != expected_members)
        ),
    }


def verify_domains(source: Path, input_manifest: dict) -> dict:
    assert input_manifest["source"] == EXPECTED_SOURCE
    records, source_utils = calibration_size_records(source, input_manifest)
    context_counts = Counter(record["context"] for record in records)
    assert dict(context_counts) == EXPECTED_CONTEXT_COUNTS
    boundary = [record for record in records if not record["theorem_domain"]]
    theorem = [record for record in records if record["theorem_domain"]]
    assert all(record["alpha_times_rank_count"] > 1.0 for record in records)
    boundary_counts = Counter(record["context"] for record in boundary)
    assert dict(boundary_counts) == EXPECTED_BOUNDARY_COUNTS
    boundary_sizes = sorted({record["n_calibration"] for record in boundary})
    characterizations = [
        characterize_boundary_size(source_utils, size, 0.05)
        for size in boundary_sizes
    ]
    # At alpha=m/(n+1), any positive strictly decreasing F normalized by
    # F(alpha)=1/alpha has mean strictly above one: its first m terms already
    # sum to at least n+1 and every later term is positive. Hence the paper
    # correctly excludes this boundary; exact AoN is the non-positive limit.
    return {
        "source": EXPECTED_SOURCE,
        "alpha": 0.05,
        "context_counts": dict(context_counts),
        "boundary_context_counts": dict(boundary_counts),
        "boundary_sizes": characterizations,
        "summary": {
            "all_contexts_accounted_for": len(records) == 1_680,
            "all_low_level_conditions_pass": all(
                record["alpha_times_rank_count"] > 1.0 for record in records
            ),
            "all_theorem_contexts_in_domain": all(
                record["theorem_domain"] for record in theorem
            ),
            "all_boundary_source_set_identities_pass": all(
                row["source_set_mismatches"] == 0 for row in characterizations
            ),
            "all_boundary_source_float_expectations_pass": all(
                abs(row["source_mean_e"] - 1.0) < 1e-12
                for row in characterizations
            ),
            "all_boundary_source_uses_upper_bracket": all(
                row["source_C"] == 1_000_000.0 for row in characterizations
            ),
            "all_exact_aon_repairs_pass": all(
                row["exact_aon_expectation"] == 1.0
                and row["exact_aon_set_mismatches"] == 0
                for row in characterizations
            ),
            "positive_exact_boundary_calibrator_impossible": True,
            "context_count": len(records),
            "theorem_context_count": len(theorem),
            "boundary_context_count": len(boundary),
            "boundary_unique_size_count": len(boundary_sizes),
            "maximum_boundary_float_deviation_from_aon": max(
                row["maximum_float_deviation_from_exact_aon"]
                for row in characterizations
            ),
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument(
        "--input-manifest", type=Path,
        default=Path("repro/configs/ca_input_manifest.json"),
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    manifest_path = (
        args.input_manifest
        if args.input_manifest.is_absolute()
        else ROOT / args.input_manifest
    )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    result = verify_domains(args.source, manifest)
    output = args.output if args.output.is_absolute() else ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(output.name + ".tmp")
    temporary.write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    temporary.replace(output)
    print(json.dumps(result["summary"], sort_keys=True))


if __name__ == "__main__":
    main()
